import { Sparkles, AlertTriangle, ShieldCheck, CloudRain, CalendarOff, Info } from 'lucide-react'

export default function InsightsPanel({ finalPlan }) {
  const dataNotes = finalPlan.dataNotes || []
  const weatherAdj = finalPlan.weatherAdjustments || []
  const unscheduled = finalPlan.unscheduledActivities || []

  return (
    <div style={{ marginTop: 20 }}>
      <div className="atlas-surface" style={{ padding: '14px 18px', display: 'flex', gap: 10, alignItems: 'center' }}>
        <Sparkles size={16} color="var(--accent)" />
        <span style={{ fontSize: 11, color: 'var(--muted)' }}>
          Why AtlasAI chose this — generated by the planning agents, not a live model call.
          {finalPlan.dataSource === 'sample' && ' Based on sample/demo travel data, not live pricing.'}
          {(finalPlan.sources?.activities === 'live' || finalPlan.sources?.activities === 'cached') && ` Places come from OpenTripMap${finalPlan.sources.activities === 'cached' ? ' (cached)' : ''}; place prices are not provided, so they are not counted in the budget.`}
        </span>
      </div>

      {/* Data notes from synthesis */}
      {dataNotes.length > 0 && (
        <div className="atlas-insight-card" style={{ borderColor: 'rgba(59,130,246,.35)' }}>
          <b style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--accent)' }}><Info size={13} /> Data notes</b>
          {dataNotes.map((note, i) => (
            <p key={i} style={{ fontSize: 12, color: 'var(--muted)' }}>{note}</p>
          ))}
        </div>
      )}

      {/* Weather adjustments */}
      {weatherAdj.length > 0 && (
        <div className="atlas-insight-card" style={{ borderColor: 'rgba(59,130,246,.35)' }}>
          <b style={{ display: 'flex', alignItems: 'center', gap: 6 }}><CloudRain size={13} /> Weather-based adjustments</b>
          {weatherAdj.map((adj, i) => (
            <p key={i} style={{ fontSize: 12 }}>
              Moved "{adj.activity}" from Day {adj.fromDay} to Day {adj.toDay} — forecast is drier on Day {adj.toDay}.
            </p>
          ))}
        </div>
      )}

      {/* Unscheduled activities */}
      {unscheduled.length > 0 && (
        <div className="atlas-insight-card" style={{ borderColor: 'rgba(245,158,11,.35)' }}>
          <b style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--color-warning, #f59e0b)' }}><CalendarOff size={13} /> Could not be scheduled</b>
          <p style={{ fontSize: 12, color: 'var(--muted)' }}>
            {unscheduled.length} activity(ies) could not fit after the estimated arrival time:
          </p>
          {unscheduled.map((act, i) => (
            <p key={i} style={{ fontSize: 12, paddingLeft: 12 }}>• {act.name || act.label || act.id}</p>
          ))}
        </div>
      )}

      {finalPlan.insights?.map((insight) => (
        <div className="atlas-insight-card" key={insight.agent}>
          <b>{insight.title}</b>
          <p>{insight.detail}</p>
        </div>
      ))}

      {!finalPlan.approved && finalPlan.remainingIssues?.length > 0 && (
        <div className="atlas-insight-card" style={{ borderColor: 'rgba(239,68,68,.35)' }}>
          <b style={{ color: 'var(--color-danger)', display: 'flex', alignItems: 'center', gap: 6 }}><AlertTriangle size={13} /> Unresolved issues</b>
          {finalPlan.remainingIssues.map((issue) => (
            <p key={issue.type}>{issue.detail || issue.type}</p>
          ))}
        </div>
      )}

      {finalPlan.safety?.data && (
        <div className="atlas-insight-card">
          <b style={{ display: 'flex', alignItems: 'center', gap: 6 }}><ShieldCheck size={13} /> Safety notes</b>
          <p>{finalPlan.safety.data.destinationRisk}. {finalPlan.safety.data.weatherNote}</p>
          {finalPlan.safety.data.forecastNotes?.length > 0 && (
            <p style={{ marginTop: 6, fontSize: 11, color: 'var(--muted)' }}>
              {finalPlan.safety.data.forecastNotes.join(' ')}
            </p>
          )}
          {finalPlan.safety.data.routeNotes?.length > 0 && (
            <p style={{ marginTop: 4, fontSize: 11, color: 'var(--muted)' }}>
              {finalPlan.safety.data.routeNotes.join(' ')}
            </p>
          )}
          {finalPlan.safety.data.transportNotes?.length > 0 && (
            <p style={{ marginTop: 4, fontSize: 11, color: 'var(--muted)' }}>
              {finalPlan.safety.data.transportNotes.join(' ')}
            </p>
          )}
          <p style={{ marginTop: 8 }}>{finalPlan.safety.data.disclaimer}</p>
        </div>
      )}

      {/* Booking disclaimer */}
      {finalPlan.bookingDisclaimer && (
        <div className="atlas-insight-card" style={{ borderColor: 'rgba(245,158,11,.25)' }}>
          <p style={{ fontSize: 11, color: 'var(--muted)', margin: 0 }}>⚠ {finalPlan.bookingDisclaimer}</p>
        </div>
      )}
    </div>
  )
}
